apiVersion: v1
kind: Service
metadata:
  name: y77hwdiff
  labels:
    run: y77hwdiff
spec:
  type: LoadBalancer
  ports:
  - port: 84
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: y77hwdiff
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: y77hwdiff
spec:
  selector:
    matchLabels:
      run: y77hwdiff
  replicas: 1
  template:
    metadata:
      labels:
        run: y77hwdiff
    spec:
      containers:
      - name: y77hwdiff-cont
        image: localhost:5000/hw_demo:1.0.0
        ports:
        - containerPort: 80
